version: '3.8'

services:
  php-apache:
    image: mysite-image
    ports:
      - "8082:80"
    deploy:
      replicas: 1
    volumes:
      - .:/var/www/html
      # - ./config/db_config.php:/var/www/html/config/db_config.php
    secrets:
      - db_password
      - db_user
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_USER_FILE: /run/secrets/db_user

secrets:
  db_password:
    external: true  
  db_user:
    external: true  


#For deepseek
# services:
#   php-apache:
#     build: .
#     ports: ["8084:90"]
#     volumes:
#       - .:/var/www/html
#       - /opt/secret-config:/secrets
#     environment:
#       DB_PASSWORD_FILE: ${DB_PASSWORD_FILE:-/run/secrets/db_password}
#       DB_USER_FILE: ${DB_USER_FILE:-/run/secrets/db_user}
#     secrets:  # Will be ignored in non-Swarm mode
#       - db_password
#       - db_user

# secrets:
#   db_password:
#     external: ${SECRETS_EXTERNAL:-false}  # Default to false
#   db_user:
#     external: ${SECRETS_EXTERNAL:-false}



# services:
#   php-apache:
#     build: .
#     ports:
#       - "8084:90"
#     volumes:
#       - .:/var/www/html  
#       - /opt/secret-config:/secrets  

      
      # - ./myapp:/var/www/html/myapp   
      # - /opt/secret-config/db_constants.php:/var/www/html/db_constants.php
#- /opt/secret-configs/sentrifugo/config.local.php:/var/www/html/application/public/config.local.php
