version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8084:90"
    volumes:
      - .:/var/www/html  
      - /opt/secret-configs/db_constants.php:/var/www/html/db_constants.php
#- /opt/secret-configs/sentrifugo/config.local.php:/var/www/html/application/public/config.local.php
